# Generated by Django 5.2.17 on 2026-09-29 11:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "student_no",
                    models.CharField(
                        max_length=32, unique=True, verbose_name="학번(아이디)"
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="이름")),
                (
                    "warnings",
                    models.PositiveIntegerField(default=0, verbose_name="누적 경고"),
                ),
                (
                    "suspended_until",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="이용 정지 종료"
                    ),
                ),
                ("created_at", models.BigIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["student_no"],
            },
        ),
        migrations.CreateModel(
            name="Seat",
            fields=[
                ("no", models.IntegerField(primary_key=True, serialize=False)),
                ("label", models.CharField(max_length=20)),
                ("x", models.IntegerField()),
                ("y", models.IntegerField()),
                ("zone", models.CharField(blank=True, default="", max_length=50)),
                ("camera_id", models.CharField(blank=True, default="", max_length=50)),
                ("qr_token", models.CharField(max_length=32)),
                ("active", models.BooleanField(default=True)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("empty", "비어 있음"),
                            ("occupied", "사람 있음"),
                            ("item", "짐만 있음"),
                            ("unavailable", "사용불가"),
                        ],
                        default="empty",
                        max_length=12,
                    ),
                ),
                ("mark", models.CharField(blank=True, max_length=5, null=True)),
                ("reason", models.CharField(blank=True, max_length=12, null=True)),
                ("note", models.CharField(blank=True, max_length=200, null=True)),
                ("state_since", models.BigIntegerField(default=0)),
                ("state_source", models.CharField(default="manual", max_length=10)),
            ],
            options={
                "ordering": ["no"],
            },
        ),
        migrations.CreateModel(
            name="Setting",
            fields=[
                (
                    "key",
                    models.CharField(max_length=40, primary_key=True, serialize=False),
                ),
                ("value", models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("reserved", "reserved"),
                            ("in_use", "in_use"),
                            ("returned", "returned"),
                            ("cancelled", "cancelled"),
                            ("expired", "expired"),
                            ("no_show", "no_show"),
                            ("force_returned", "force_returned"),
                        ],
                        max_length=16,
                    ),
                ),
                ("start_at", models.BigIntegerField()),
                ("end_at", models.BigIntegerField()),
                ("checked_in_at", models.BigIntegerField(blank=True, null=True)),
                ("ended_at", models.BigIntegerField(blank=True, null=True)),
                ("extend_count", models.IntegerField(default=0)),
                ("source", models.CharField(default="map", max_length=10)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reservations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "seat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reservations",
                        to="seats.seat",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SeatState",
            fields=[
                (
                    "seat",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="seats.seat",
                    ),
                ),
                ("seat_state", models.CharField(max_length=12)),
                ("detail", models.CharField(max_length=20)),
                ("since", models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("unauthorized", "unauthorized"),
                            ("no_checkin", "no_checkin"),
                            ("away", "away"),
                            ("hoarding", "hoarding"),
                            ("seat_unavailable", "seat_unavailable"),
                            ("no_show", "no_show"),
                            ("call", "call"),
                        ],
                        max_length=20,
                    ),
                ),
                ("memo", models.CharField(blank=True, max_length=200, null=True)),
                ("created_at", models.BigIntegerField()),
                ("resolved_at", models.BigIntegerField(blank=True, null=True)),
                ("resolution", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reservation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="seats.reservation",
                    ),
                ),
                (
                    "seat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="alerts",
                        to="seats.seat",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AdminLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=20)),
                ("reservation_id", models.BigIntegerField(null=True)),
                ("alert_id", models.BigIntegerField(null=True)),
                ("memo", models.CharField(max_length=300, null=True)),
                ("at", models.BigIntegerField(db_index=True)),
                (
                    "admin",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "seat",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="seats.seat",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StatusLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("seat_no", models.IntegerField()),
                ("seat_state", models.CharField(max_length=12)),
                ("detail", models.CharField(max_length=20)),
                ("prev_detail", models.CharField(max_length=20, null=True)),
                ("reservation_id", models.BigIntegerField(null=True)),
                ("actual", models.CharField(max_length=12, null=True)),
                ("at", models.BigIntegerField()),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["seat_no", "at"], name="seats_statu_seat_no_c4adf2_idx"
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="reservation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status__in", ("reserved", "in_use"))),
                fields=("seat",),
                name="ux_res_active_seat",
            ),
        ),
        migrations.AddConstraint(
            model_name="reservation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status__in", ("reserved", "in_use"))),
                fields=("user",),
                name="ux_res_active_user",
            ),
        ),
        migrations.AddConstraint(
            model_name="alert",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("resolved_at__isnull", True),
                    models.Q(("type", "call"), _negated=True),
                ),
                fields=("seat", "type"),
                name="ux_alert_open",
            ),
        ),
    ]
