# Generated by Django 5.2.17 on 2026-09-29 12:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seats", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="JudgmentFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("at", models.BigIntegerField(db_index=True)),
                ("shown_state", models.CharField(max_length=12)),
                ("shown_detail", models.CharField(max_length=20)),
                ("source", models.CharField(max_length=10)),
                ("verdict", models.CharField(max_length=8)),
                (
                    "correct_detail",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("memo", models.CharField(blank=True, max_length=200, null=True)),
                ("applied", models.BooleanField(default=False)),
                (
                    "admin",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "seat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback",
                        to="seats.seat",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kind", models.CharField(max_length=20)),
                ("level", models.CharField(default="info", max_length=8)),
                ("title", models.CharField(max_length=100)),
                ("body", models.CharField(blank=True, default="", max_length=300)),
                (
                    "dedup_key",
                    models.CharField(blank=True, max_length=80, null=True, unique=True),
                ),
                ("created_at", models.BigIntegerField()),
                ("read_at", models.BigIntegerField(blank=True, null=True)),
                (
                    "reservation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="seats.reservation",
                    ),
                ),
                (
                    "seat",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="seats.seat",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user", "created_at"],
                        name="seats_notif_user_id_b40196_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ReservationEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kind", models.CharField(max_length=16)),
                ("at", models.BigIntegerField()),
                ("memo", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "reservation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="seats.reservation",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user", "at"], name="seats_reser_user_id_e96347_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="WaitEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("zone", models.CharField(blank=True, default="", max_length=50)),
                ("status", models.CharField(default="waiting", max_length=10)),
                ("created_at", models.BigIntegerField()),
                ("offered_at", models.BigIntegerField(blank=True, null=True)),
                ("expires_at", models.BigIntegerField(blank=True, null=True)),
                ("ended_at", models.BigIntegerField(blank=True, null=True)),
                (
                    "offered_seat",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="seats.seat",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wait_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status__in", ("waiting", "offered"))),
                        fields=("user",),
                        name="ux_wait_active_user",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("status", "offered")),
                        fields=("offered_seat",),
                        name="ux_wait_offer_seat",
                    ),
                ],
            },
        ),
    ]
