# Generated by Django 5.2.17 on 2026-09-29 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seats", "0002_history_waitlist_feedback"),
    ]

    operations = [
        migrations.CreateModel(
            name="Camera",
            fields=[
                (
                    "camera_id",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("health", models.CharField(default="", max_length=30)),
                ("meaning", models.CharField(default="", max_length=40)),
                ("schema_version", models.IntegerField(null=True)),
                ("observed_at", models.BigIntegerField(null=True)),
                ("valid_until", models.BigIntegerField(null=True)),
                ("last_seen_at", models.BigIntegerField(null=True)),
                ("clock_offset", models.IntegerField(default=0)),
                ("seats_reported", models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name="judgmentfeedback",
            name="cam_confidence",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="judgmentfeedback",
            name="cam_state",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="seat",
            name="cam_confidence",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="seat",
            name="cam_seen_at",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="seat",
            name="cam_state",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="seat",
            name="cam_unknown_since",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="seat",
            name="cam_valid_until",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="seat",
            name="camera_seat",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
    ]
