# Generated by Django 5.2.17 on 2026-10-01 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seats", "0003_camera_integration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alert",
            name="type",
            field=models.CharField(
                choices=[
                    ("unauthorized", "unauthorized"),
                    ("no_checkin", "no_checkin"),
                    ("away", "away"),
                    ("hoarding", "hoarding"),
                    ("unknown", "unknown"),
                    ("seat_unavailable", "seat_unavailable"),
                    ("no_show", "no_show"),
                    ("call", "call"),
                ],
                max_length=20,
            ),
        ),
    ]
