# Generated by Django 5.2.17 on 2026-10-01 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seats", "0004_alert_unknown"),
    ]

    operations = [
        migrations.AddField(
            model_name="alert",
            name="call_kind",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
    ]
