# Generated by Django 5.2.17 on 2026-10-01 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seats", "0005_alert_call_kind"),
    ]

    operations = [
        migrations.AddField(
            model_name="camera",
            name="item_meaning",
            field=models.CharField(default="", max_length=40),
        ),
        migrations.AddField(
            model_name="seat",
            name="cam_item",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="seat",
            name="cam_item_confidence",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
