# Generated by Django 5.2.17 on 2026-10-01 15:36

import time

from django.db import migrations, models


def close_unowned_alerts(apps, schema_editor):
    """'주인 없는 짐' 상태를 없앤다 — 열려 있던 알림은 처리 완료로 닫는다."""
    Alert = apps.get_model("seats", "Alert")
    Alert.objects.filter(type="unowned_item", resolved_at__isnull=True).update(
        resolved_at=int(time.time()), resolution="auto")


class Migration(migrations.Migration):

    dependencies = [
        ("seats", "0007_alert_unowned_item"),
    ]

    operations = [
        migrations.RunPython(close_unowned_alerts, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="alert",
            name="type",
            field=models.CharField(
                choices=[
                    ("unauthorized", "unauthorized"),
                    ("no_checkin", "no_checkin"),
                    ("away", "away"),
                    ("hoarding", "hoarding"),
                    ("unknown", "unknown"),
                    ("seat_unavailable", "seat_unavailable"),
                    ("no_show", "no_show"),
                    ("call", "call"),
                ],
                max_length=20,
            ),
        ),
    ]
